// Generated by CoffeeScript 1.12.4
var gulp, gulpRename, readify;

readify = require('readify');

gulp = require('gulp');

gulpRename = require('gulp-rename');

readify('./raw/', {
  type: 'raw',
  sort: 'date',
  order: 'desc'
}, function(error, data) {
  var i, results;
  i = 0;
  results = [];
  while (i < data.files.length) {
    gulp.src(data.path + data.files[i].name).pipe(gulpRename(i + '.jpg')).pipe(gulp.dest('./'));
    results.push(i++);
  }
  return results;
});
