// Generated by CoffeeScript 1.12.4
var addNumPhoto, collageContainer, i, j, ref;



addNumPhoto = function(obj, num) {
  var wAppend;
  wAppend = $('<div class="Image_Wrapper"><a onclick="imagePopup(\'./img/' + num + '.jpg\')"><img src="./img/' + num + '.jpg"></a></div>');
  return obj.append(wAppend);
};

collageContainer = $('#collageContainer');

for (i = 0, ref = NUM_OF_PICTURES; i < ref; i++) {
  addNumPhoto(collageContainer, i);
}
