// Generated by CoffeeScript 1.12.4
var NUM_OF_PICTURES, addNumPhoto, collageContainer, i, j, ref;

NUM_OF_PICTURES = 13;

addNumPhoto = function(obj, num) {
  var wAppend;
  wAppend = $('<div class="Image_Wrapper"><a onclick="imagePopup(\'./img/' + num + '.jpg\')"><img src="./img/' + num + '.jpg"></a></div>');
  return obj.append(wAppend);
};

collageContainer = $('#collageContainer');

for (i = j = 0, ref = NUM_OF_PICTURES; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
  addNumPhoto(collageContainer, i);
}
