// Generated by CoffeeScript 1.12.4
var collage, resizeTimer;

collage = function() {
  $('.Collage').removeWhitespace().collagePlus({
    'fadeSpeed': 2000,
    'targetHeight': 200,
    'effect': 'effect-6',
    'direction': 'vertical'
  });
};

$(window).load(function() {
  $(document).ready(function() {
    collage();
    $('.Collage').collageCaption();
  });
});

resizeTimer = null;

$(window).bind('resize', function() {
  $('.Collage .Image_Wrapper').css('opacity', 0);
  if (resizeTimer) {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(collage, 200);
  }
});
